{% set name = "seqlog" %}
{% set version = "0.3.25" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a5a543ac08db01a8b9e48bbf225e6717471024e669419951d8afe92224e775db

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - python-dateutil >=2.5.3
    - pyyaml >=3.11
    - requests >=2.10.0

test:
  imports:
    - seqlog
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/tintoy/seqlog
  summary: SeqLog enables logging from Python to Seq.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - dhirschfeld
