{% set name = "seqlog" %}
{% set version = "0.4.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d53341e1ac24211d4f715fd824e2e5b38378709d90363f85f65a63de166c7c0e

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}
    - python-dateutil >=2.5.3
    - pyyaml >=3.11
    - requests >=2.10.0

test:
  imports:
    - seqlog
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/tintoy/seqlog
  summary: SeqLog enables logging from Python to Seq.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - dhirschfeld
